# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QT/Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1550, 923)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("\n"
"/*\n"
"    COLOR_DARK     = #191919\n"
"    COLOR_MEDIUM   = #353535\n"
"    COLOR_MEDLIGHT = #5A5A5A\n"
"    COLOR_LIGHT    = #DDDDDD\n"
"    COLOR_ACCENT   = #3D7848\n"
"    \n"
"    COLOR_BLUEDARK = #0F044C\n"
"    COLOR_BLUELIGHT = #141E61\n"
"*/\n"
"\n"
"\n"
"\n"
"* {\n"
"    background: #191919;\n"
"    color: #DDDDDD;\n"
"    border: 1px solid #5A5A5A;\n"
"    border-radius: 5px; \n"
"    font: 11pt \"Segoe UI Semilight\";\n"
"}\n"
"QLabel {\n"
"    border: none; \n"
"}\n"
"\n"
"QWidget::item:selected {\n"
"    background: #3D7848;\n"
"}\n"
"\n"
"QCheckBox, QRadioButton {\n"
"    border: none;\n"
"}\n"
"\n"
"QRadioButton::indicator, QCheckBox::indicator {\n"
"    width: 13px;\n"
"    height: 13px;\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked, QCheckBox::indicator::unchecked {\n"
"    border: 1px solid #5A5A5A;\n"
"    background: none;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover, QCheckBox::indicator:unchecked:hover {\n"
"    border: 1px solid #DDDDDD;\n"
"}\n"
"\n"
"QRadioButton::indicator::checked, QCheckBox::indicator::checked {\n"
"    border: 1px solid #5A5A5A;\n"
"    background: #5A5A5A;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover, QCheckBox::indicator:checked:hover {\n"
"    border: 1px solid #DDDDDD;\n"
"    background: #DDDDDD;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    margin-top: 6px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    top: -7px;\n"
"    left: 7px;\n"
"}\n"
"\n"
"QScrollBar {\n"
"    border: 1px solid #5A5A5A;\n"
"    background: #191919;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 15px;\n"
"    margin: 0px 0px 0px 32px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    width: 15px;\n"
"    margin: 32px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: #353535;\n"
"    border: 1px solid #5A5A5A;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    border-width: 0px 1px 0px 1px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    border-width: 1px 0px 1px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background:#353535;\n"
"    border: 1px solid #5A5A5A;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line {\n"
"    position: absolute;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 15px;\n"
"    subcontrol-position: left;\n"
"    left: 15px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    top: 15px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 15px;\n"
"    subcontrol-position: top left;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"}\n"
"\n"
"QScrollBar:left-arrow, QScrollBar::right-arrow, QScrollBar::up-arrow, QScrollBar::down-arrow {\n"
"    border: 1px solid #5A5A5A;\n"
"    width: 3px;\n"
"    height: 3px;\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: none;\n"
"}\n"
"\n"
"QAbstractButton:hover {\n"
"    background: #353535;\n"
"}\n"
"\n"
"QAbstractButton:pressed {\n"
"    background: #5A5A5A;\n"
"}\n"
"\n"
"QAbstractItemView {\n"
"    show-decoration-selected: 1;\n"
"    selection-background-color: #3D7848;\n"
"    selection-color: #DDDDDD;\n"
"    alternate-background-color: #353535;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    border: 1px solid #5A5A5A;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: #191919;\n"
"    border: 1px solid #5A5A5A;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QHeaderView::section:selected, QHeaderView::section::checked {\n"
"    background: #353535;\n"
"}\n"
"\n"
"QTableView {\n"
"    gridline-color: #5A5A5A;\n"
"}\n"
"\n"
"QTabBar {\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-radius: 0px;\n"
"    padding: 4px;\n"
"    margin: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #353535;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    border: 1px solid #5A5A5A;\n"
"    background: #353535;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: 1px solid #5A5A5A;\n"
"    background: #353535;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 3px;\n"
"    height: 3px;\n"
"    border: 1px solid #5A5A5A;\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    padding-right: 15px;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-button, QAbstractSpinBox::down-button {\n"
"    border: 1px solid #5A5A5A;\n"
"    background: #353535;\n"
"    subcontrol-origin: border;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow, QAbstractSpinBox::down-arrow {\n"
"    width: 3px;\n"
"    height: 3px;\n"
"    border: 1px solid #5A5A5A;\n"
"}\n"
"\n"
"QSlider {\n"
"    border: none;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    margin: 4px 0px 4px 0px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    margin: 0px 4px 0px 4px;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    border: 1px solid #5A5A5A;\n"
"    background: #353535;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    width: 15px;\n"
"    margin: -4px 0px -4px 0px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    height: 15px;\n"
"    margin: 0px -4px 0px -4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical, QSlider::sub-page:horizontal {\n"
"    background: #3D7848;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical, QSlider::add-page:horizontal {\n"
"    background: #353535;\n"
"}\n"
"\n"
"QLabel {\n"
"    border: none;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    width: 1px;\n"
"    background-color: #3D7848;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    background: #353535;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    font-family:\'Segoe UI Semilight\'; \n"
"    font-size:12pt; \n"
"    font-weight:600;\n"
"     font-style:normal;\n"
"}\n"
"QPushButton {\n"
"    font-family:\'Segoe UI Semilight\'; \n"
"    font-size:12pt; \n"
"    font-weight:800;\n"
"    font-style:normal;\n"
"    background: #0F044C;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 300))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Home_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_Home_2.sizePolicy().hasHeightForWidth())
        self.tab_Home_2.setSizePolicy(sizePolicy)
        self.tab_Home_2.setStyleSheet("border: none")
        self.tab_Home_2.setObjectName("tab_Home_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_Home_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.txt_tryVideo = QtWidgets.QTextEdit(self.tab_Home_2)
        self.txt_tryVideo.setLineWidth(0)
        self.txt_tryVideo.setObjectName("txt_tryVideo")
        self.gridLayout_7.addWidget(self.txt_tryVideo, 3, 1, 1, 1)
        self.Btn_VideoDet_2 = QtWidgets.QPushButton(self.tab_Home_2)
        self.Btn_VideoDet_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.Btn_VideoDet_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./QT\\assets/video1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_VideoDet_2.setIcon(icon)
        self.Btn_VideoDet_2.setIconSize(QtCore.QSize(300, 300))
        self.Btn_VideoDet_2.setObjectName("Btn_VideoDet_2")
        self.gridLayout_7.addWidget(self.Btn_VideoDet_2, 4, 1, 1, 1)
        self.Btn_WebcamDet_2 = QtWidgets.QPushButton(self.tab_Home_2)
        self.Btn_WebcamDet_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.Btn_WebcamDet_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./QT\\assets/webcam1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_WebcamDet_2.setIcon(icon1)
        self.Btn_WebcamDet_2.setIconSize(QtCore.QSize(300, 300))
        self.Btn_WebcamDet_2.setObjectName("Btn_WebcamDet_2")
        self.gridLayout_7.addWidget(self.Btn_WebcamDet_2, 4, 2, 1, 1)
        self.txt_Home = QtWidgets.QTextEdit(self.tab_Home_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.txt_Home.setFont(font)
        self.txt_Home.setLineWidth(0)
        self.txt_Home.setObjectName("txt_Home")
        self.gridLayout_7.addWidget(self.txt_Home, 1, 0, 1, 3)
        self.Btn_ImageDet_2 = QtWidgets.QPushButton(self.tab_Home_2)
        self.Btn_ImageDet_2.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.Btn_ImageDet_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./QT\\assets/image1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_ImageDet_2.setIcon(icon2)
        self.Btn_ImageDet_2.setIconSize(QtCore.QSize(300, 300))
        self.Btn_ImageDet_2.setObjectName("Btn_ImageDet_2")
        self.gridLayout_7.addWidget(self.Btn_ImageDet_2, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(80, 60, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 2, 0, 1, 3)
        self.txt_tryImage = QtWidgets.QTextEdit(self.tab_Home_2)
        self.txt_tryImage.setLineWidth(0)
        self.txt_tryImage.setObjectName("txt_tryImage")
        self.gridLayout_7.addWidget(self.txt_tryImage, 3, 0, 1, 1)
        self.txt_tryWebcam = QtWidgets.QTextEdit(self.tab_Home_2)
        self.txt_tryWebcam.setLineWidth(0)
        self.txt_tryWebcam.setObjectName("txt_tryWebcam")
        self.gridLayout_7.addWidget(self.txt_tryWebcam, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 100, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 5, 0, 1, 3)
        self.tabWidget.addTab(self.tab_Home_2, "")
        self.tab_ImageDet = QtWidgets.QWidget()
        self.tab_ImageDet.setObjectName("tab_ImageDet")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_ImageDet)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.combo_chooseDevice = QtWidgets.QComboBox(self.tab_ImageDet)
        self.combo_chooseDevice.setObjectName("combo_chooseDevice")
        self.gridLayout_8.addWidget(self.combo_chooseDevice, 6, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_ImageDet)
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_8.addWidget(self.comboBox_3, 14, 1, 1, 1)
        self.txt_ImageDet = QtWidgets.QTextEdit(self.tab_ImageDet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_ImageDet.sizePolicy().hasHeightForWidth())
        self.txt_ImageDet.setSizePolicy(sizePolicy)
        self.txt_ImageDet.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.txt_ImageDet.setFont(font)
        self.txt_ImageDet.setLineWidth(0)
        self.txt_ImageDet.setObjectName("txt_ImageDet")
        self.gridLayout_8.addWidget(self.txt_ImageDet, 0, 0, 1, 3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_ImageDet)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_8.addWidget(self.lineEdit_2, 19, 0, 1, 2)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_ImageDet)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_8.addWidget(self.comboBox_6, 17, 0, 1, 1)
        self.combo_chooseUserModel = QtWidgets.QComboBox(self.tab_ImageDet)
        self.combo_chooseUserModel.setEditable(False)
        self.combo_chooseUserModel.setCurrentText("")
        self.combo_chooseUserModel.setObjectName("combo_chooseUserModel")
        self.gridLayout_8.addWidget(self.combo_chooseUserModel, 14, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 2, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_ImageDet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_8.addWidget(self.lineEdit_3, 17, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 2, 2, 1, 1)
        self.btn_addImage = QtWidgets.QPushButton(self.tab_ImageDet)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.btn_addImage.setFont(font)
        self.btn_addImage.setStyleSheet("")
        self.btn_addImage.setObjectName("btn_addImage")
        self.gridLayout_8.addWidget(self.btn_addImage, 26, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 11, 2, 1, 1)
        self.combo_api = QtWidgets.QComboBox(self.tab_ImageDet)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.combo_api.setFont(font)
        self.combo_api.setEditable(False)
        self.combo_api.setObjectName("combo_api")
        self.combo_api.addItem("")
        self.combo_api.addItem("")
        self.gridLayout_8.addWidget(self.combo_api, 6, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_ImageDet)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_8.addWidget(self.pushButton_2, 15, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 16, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_10.setMinimumSize(QtCore.QSize(700, 0))
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 11, 0, 1, 2)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_ImageDet)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_8.addWidget(self.comboBox_5, 22, 0, 1, 1)
        self.combo_model = QtWidgets.QComboBox(self.tab_ImageDet)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.combo_model.setFont(font)
        self.combo_model.setEditable(False)
        self.combo_model.setObjectName("combo_model")
        self.combo_model.addItem("")
        self.combo_model.addItem("")
        self.combo_model.addItem("")
        self.combo_model.addItem("")
        self.gridLayout_8.addWidget(self.combo_model, 10, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 16, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.tab_ImageDet)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.pushButton, 15, 0, 1, 1)
        self.btn_process = QtWidgets.QPushButton(self.tab_ImageDet)
        self.btn_process.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_process.setFont(font)
        self.btn_process.setStyleSheet("font:\"Segoe UI Semilight\"; \n"
"font-size: 12\n"
"")
        self.btn_process.setObjectName("btn_process")
        self.gridLayout_8.addWidget(self.btn_process, 26, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 18, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 21, 1, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_ImageDet)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_8.addWidget(self.comboBox_8, 22, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_ImageDet)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 2, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.tab_ImageDet)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_8.addWidget(self.textEdit, 14, 2, 5, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_ImageDet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 9, 0, 1, 2)
        self.list_status = QtWidgets.QListWidget(self.tab_ImageDet)
        self.list_status.setObjectName("list_status")
        self.gridLayout_8.addWidget(self.list_status, 5, 2, 6, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 21, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_ImageDet)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 19, 2, 1, 1)
        self.lb_image_orig = QtWidgets.QLabel(self.tab_ImageDet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_image_orig.sizePolicy().hasHeightForWidth())
        self.lb_image_orig.setSizePolicy(sizePolicy)
        self.lb_image_orig.setMinimumSize(QtCore.QSize(700, 500))
        self.lb_image_orig.setText("")
        self.lb_image_orig.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_image_orig.setObjectName("lb_image_orig")
        self.gridLayout_8.addWidget(self.lb_image_orig, 21, 2, 5, 1)
        self.list_filenames = QtWidgets.QListWidget(self.tab_ImageDet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_filenames.sizePolicy().hasHeightForWidth())
        self.list_filenames.setSizePolicy(sizePolicy)
        self.list_filenames.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.list_filenames.setFont(font)
        self.list_filenames.setLineWidth(0)
        self.list_filenames.setObjectName("list_filenames")
        self.gridLayout_8.addWidget(self.list_filenames, 24, 0, 1, 2)
        self.tabWidget.addTab(self.tab_ImageDet, "")
        self.tab_Results = QtWidgets.QWidget()
        self.tab_Results.setObjectName("tab_Results")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_Results)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.tab_Results)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lb_image_res = QtWidgets.QLabel(self.tab_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_image_res.sizePolicy().hasHeightForWidth())
        self.lb_image_res.setSizePolicy(sizePolicy)
        self.lb_image_res.setMinimumSize(QtCore.QSize(700, 400))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lb_image_res.setFont(font)
        self.lb_image_res.setText("")
        self.lb_image_res.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_image_res.setObjectName("lb_image_res")
        self.verticalLayout.addWidget(self.lb_image_res)
        self.ln_ObjectCount = QtWidgets.QLineEdit(self.tab_Results)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ln_ObjectCount.setFont(font)
        self.ln_ObjectCount.setObjectName("ln_ObjectCount")
        self.verticalLayout.addWidget(self.ln_ObjectCount)
        self.label_8 = QtWidgets.QLabel(self.tab_Results)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.txt_PredDump = QtWidgets.QTextEdit(self.tab_Results)
        self.txt_PredDump.setObjectName("txt_PredDump")
        self.verticalLayout.addWidget(self.txt_PredDump)
        self.btn_openImageDialog = QtWidgets.QPushButton(self.tab_Results)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_openImageDialog.sizePolicy().hasHeightForWidth())
        self.btn_openImageDialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.btn_openImageDialog.setFont(font)
        self.btn_openImageDialog.setObjectName("btn_openImageDialog")
        self.verticalLayout.addWidget(self.btn_openImageDialog)
        self.tabWidget.addTab(self.tab_Results, "")
        self.tab_WebcamDet = QtWidgets.QWidget()
        self.tab_WebcamDet.setObjectName("tab_WebcamDet")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_WebcamDet)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_startWebcamDet = QtWidgets.QPushButton(self.tab_WebcamDet)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.btn_startWebcamDet.setFont(font)
        self.btn_startWebcamDet.setObjectName("btn_startWebcamDet")
        self.gridLayout.addWidget(self.btn_startWebcamDet, 2, 1, 1, 1)
        self.lb_webcamDet = QtWidgets.QLabel(self.tab_WebcamDet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_webcamDet.sizePolicy().hasHeightForWidth())
        self.lb_webcamDet.setSizePolicy(sizePolicy)
        self.lb_webcamDet.setMinimumSize(QtCore.QSize(600, 400))
        self.lb_webcamDet.setText("")
        self.lb_webcamDet.setObjectName("lb_webcamDet")
        self.gridLayout.addWidget(self.lb_webcamDet, 4, 1, 1, 1)
        self.txt_WebcamHeading = QtWidgets.QTextEdit(self.tab_WebcamDet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_WebcamHeading.sizePolicy().hasHeightForWidth())
        self.txt_WebcamHeading.setSizePolicy(sizePolicy)
        self.txt_WebcamHeading.setObjectName("txt_WebcamHeading")
        self.gridLayout.addWidget(self.txt_WebcamHeading, 0, 0, 1, 2)
        self.lb_webcam = QtWidgets.QLabel(self.tab_WebcamDet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_webcam.sizePolicy().hasHeightForWidth())
        self.lb_webcam.setSizePolicy(sizePolicy)
        self.lb_webcam.setMinimumSize(QtCore.QSize(600, 400))
        self.lb_webcam.setText("")
        self.lb_webcam.setObjectName("lb_webcam")
        self.gridLayout.addWidget(self.lb_webcam, 4, 0, 1, 1)
        self.btn_startWebcam = QtWidgets.QPushButton(self.tab_WebcamDet)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.btn_startWebcam.setFont(font)
        self.btn_startWebcam.setStyleSheet("")
        self.btn_startWebcam.setObjectName("btn_startWebcam")
        self.gridLayout.addWidget(self.btn_startWebcam, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab_WebcamDet)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.btn_stopWebcam = QtWidgets.QPushButton(self.tab_WebcamDet)
        self.btn_stopWebcam.setObjectName("btn_stopWebcam")
        self.gridLayout.addWidget(self.btn_stopWebcam, 3, 0, 1, 1)
        self.btn_stopWebcamDet = QtWidgets.QPushButton(self.tab_WebcamDet)
        self.btn_stopWebcamDet.setObjectName("btn_stopWebcamDet")
        self.gridLayout.addWidget(self.btn_stopWebcamDet, 3, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab_WebcamDet, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionVideo_Detection = QtWidgets.QAction(MainWindow)
        self.actionVideo_Detection.setObjectName("actionVideo_Detection")
        self.actionImage_Detection = QtWidgets.QAction(MainWindow)
        self.actionImage_Detection.setObjectName("actionImage_Detection")
        self.actionLive_Webcam_Detection = QtWidgets.QAction(MainWindow)
        self.actionLive_Webcam_Detection.setObjectName("actionLive_Webcam_Detection")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.combo_model.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DemonstrationNeuronalNetworks"))
        self.txt_tryVideo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semilight\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:400;\">try object detection on videos</span></p></body></html>"))
        self.txt_Home.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semilight\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:400;\">HOME</span></p></body></html>"))
        self.txt_tryImage.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semilight\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:400;\">try object detection on images</span></p></body></html>"))
        self.txt_tryWebcam.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semilight\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:400;\">try object detection on your webcam</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Home_2), _translate("MainWindow", "Start"))
        self.comboBox_3.setPlaceholderText(_translate("MainWindow", "choose weights"))
        self.txt_ImageDet.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semilight\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:400;\">Image Detection</span></p></body></html>"))
        self.combo_chooseUserModel.setPlaceholderText(_translate("MainWindow", "choose model"))
        self.label_9.setText(_translate("MainWindow", "Choose device"))
        self.label_7.setText(_translate("MainWindow", "Info "))
        self.btn_addImage.setText(_translate("MainWindow", "Add data"))
        self.label_14.setText(_translate("MainWindow", "Model Info"))
        self.combo_api.setPlaceholderText(_translate("MainWindow", "Choose an API"))
        self.combo_api.setItemText(0, _translate("MainWindow", "OpenMMLab"))
        self.combo_api.setItemText(1, _translate("MainWindow", "Tensorflow"))
        self.pushButton_2.setText(_translate("MainWindow", "upload weights"))
        self.label_12.setText(_translate("MainWindow", "Specify threshhold"))
        self.label_10.setText(_translate("MainWindow", "or use your own "))
        self.combo_model.setPlaceholderText(_translate("MainWindow", "Choose a model"))
        self.combo_model.setItemText(0, _translate("MainWindow", "Choose a model"))
        self.combo_model.setItemText(1, _translate("MainWindow", "Yolov3 with OpenMMLab"))
        self.combo_model.setItemText(2, _translate("MainWindow", "Faster rcnn r50 with OpenMMLab"))
        self.combo_model.setItemText(3, _translate("MainWindow", "Yolov4 with Tensorflow"))
        self.label_15.setText(_translate("MainWindow", "Specify batchsize"))
        self.pushButton.setText(_translate("MainWindow", "upload model"))
        self.btn_process.setText(_translate("MainWindow", "Process Data"))
        self.label_13.setText(_translate("MainWindow", "Specify output directory"))
        self.label_11.setText(_translate("MainWindow", "or choose dataset"))
        self.label.setText(_translate("MainWindow", "Choose an API"))
        self.label_2.setText(_translate("MainWindow", "Choose a model "))
        self.label_3.setText(_translate("MainWindow", "Choose images"))
        self.label_5.setText(_translate("MainWindow", "Original Image: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ImageDet), _translate("MainWindow", "Image Detection"))
        self.label_6.setText(_translate("MainWindow", "Processed Image: "))
        self.ln_ObjectCount.setText(_translate("MainWindow", "Objects Detected: "))
        self.label_8.setText(_translate("MainWindow", "Predictions Info"))
        self.btn_openImageDialog.setText(_translate("MainWindow", "Open result in Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Results), _translate("MainWindow", "Results"))
        self.btn_startWebcamDet.setText(_translate("MainWindow", "Start Detection"))
        self.txt_WebcamHeading.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semilight\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Live Webcam Detection</p></body></html>"))
        self.btn_startWebcam.setText(_translate("MainWindow", "Start Webcam"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Choose a type of Detection"))
        self.comboBox.setItemText(1, _translate("MainWindow", "TechVidvan Hand Gesture Detection"))
        self.comboBox.setItemText(2, _translate("MainWindow", "OpenMMLab Video Detection YOLOV3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "OpenMMLab Video Detection FasterRCNN"))
        self.btn_stopWebcam.setText(_translate("MainWindow", "Stop Webcam"))
        self.btn_stopWebcamDet.setText(_translate("MainWindow", "Stop Detection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_WebcamDet), _translate("MainWindow", "Live-Webcam Detection"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionVideo_Detection.setText(_translate("MainWindow", "Video Detection"))
        self.actionImage_Detection.setText(_translate("MainWindow", "Image Detection"))
        self.actionLive_Webcam_Detection.setText(_translate("MainWindow", "Live-Webcam Detection"))
